identifier: noru64_v1_single
name: Noru64 V1 Single
type: keyboard
architecture: arm
url: https://github.com/zmkfirmware/zmk
features:
  - bluetooth
  - rgb_underglow
  - battery
  - usb
  - backlight
  - external_power
build_system: zephyr
supported_software:
  - zmk
