name: Build Firmware

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: noru64_v1_single
          - board: noru64_v1_left
          - board: noru64_v1_right
          - board: nice_nano
            shield: settings_reset

    steps:
      - name: Checkout ZMK
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          submodules: true

      - name: Checkout User Config
        uses: actions/checkout@v4
        with:
          path: config
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install west

      - name: Initialize Zephyr
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Install Zephyr SDK
        run: |
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Build
        run: |
          if [ -n "${{ matrix.shield }}" ]; then
            west build -d build/${{ matrix.board }}/${{ matrix.shield }} -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG=$PWD/config
          else
            west build -d build/${{ matrix.board }} -b ${{ matrix.board }} -- -DZMK_CONFIG=$PWD/config
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.board }}${{ matrix.shield && format('-{0}', matrix.shield) || '' }}
          path: build/${{ matrix.board }}${{ matrix.shield && format('/{0}', matrix.shield) || '' }}/zephyr/zmk.uf2
